version: 2

sphinx:
  configuration: docs/source/conf.py

python:
  version: 3.8
  install:
    - requirements: requirements.txt

build:
  os: ubuntu-22.04 # macOS
  tools:
    python: "3.8"
    # pip: "20.0.2"