version: 2

sphinx:
  configuration: docs/source/conf.py

python:
  install:
    # - requirements: requirements.txt
      - method: conda
        path: environment.yml


build:
  os: ubuntu-22.04
  tools:
    python: "3.10"