version: 2

sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - requirements: requirements.txt

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"


# build:
#   os: ubuntu-22.04
#   tools:
#     python: "3.10" # This sets the Python version used by Read the Docs for its build processes.
#                   # Your conda environment.yml should also specify a compatible python version.
#   conda:
#     environment: environment.yml # Path to your conda environment file
