version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  # apt_packages: # Keep if needed for dependencies like POT
  #   - build-essential

sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - requirements: docs/requirements.txt # Install documentation requirements first
    - method: pip
      path: .        # Correctly specify the path to the package root
                     # This will run 'pip install .' which installs your package