name: TEST_gait_modulation
channels:
  - conda-forge
  - defaults
  - apple
dependencies:
  - python=3.10
  - antropy==0.1.9
  - imbalanced-learn==0.12.4
  - keras==3.9.0
  - matplotlib==3.8.4
  - mne==1.7.1
  - numpy==1.26.4
  - pandas==2.2.1
  - scikit-learn==1.5.1
  - scipy==1.13.0
  - setuptools==69.5.1
  - tqdm==4.66.4
  - conda:
    - tensorflow-deps
  - pip:
      # - tensorflow==2.16.2
      - tensorflow-macos==2.16.2
      - tensorflow-metal==1.2.0
      # - imbalanced-learn==0.12.4
      # - scikit-learn==1.5.1
      - -e .
    # - gait_modulation

# prefix: /Users/orabe/miniconda3/envs/gait_modulation
